#!/bin/bash

# Internet Archive Plugin for Bashflix

# This requires user to install ia

resource="The Internet Archive"

# This fetches and displays results
results=$(ia search "$query" | head -n 10 | cut -c 16- | nl | cut -c 4)
echo results

results=$($results | head -n 1 | cut -c 5-)
magnet=${results%?}
